### ISSUE TITLE
Other Audiences

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-audiences#1]
Potential:
- [x] people with disabilities
- [x] trainers
- [x] advocates
- [ ] ...

**Comment by nitedog** [comment]
issue #2 

and also !!! for trainers/educators

**Comment by slhenry** [comment]
Draft https://w3c.github.io/wai-audiences/audiences/users/

**Comment by slhenry** [comment]
Closing for now. Feel free to re-open if you have other ideas.
