### ISSUE TITLE
[ED] something not "clicking"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-audiences#3]
I think it is good to have role-based orientation guidance.

However, I find it seems fairly limiting and constraining rather than helpful:

- I don't understand why some things are or are not listed. For example, "business case" not listed for managers seems odd. Also "how people with disabilities use the web" is not referenced at all.
- most sections seem to assume newbie and kind of "talks down". ie. "first, skim..." or "to understand...". several audiences, including managers and policy makers are more advanced than this.

Not sure what to suggest, which is why only marked this as "ED", but feel it is fairly significant. Either we need to phrase this entire things as "first steps for <audience>" and/or add "these are some initial materials" and add hints for "further reading" or "related materials". The entire approach needs to be more open and accommodating to the wide ranges of different roles within these categories, and the wide ranges of different skills and knowledge among them.

**Comment by slhenry** [comment]
Thanks for the input, Shadi.

I've added this to the [F2F agenda](https://www.w3.org/WAI/EO/wiki/EOWG_F2F_March_2018#Materials_to_read_in_preparation). 

One point: An initial idea had more links. However, many of those -- including How People with Disabilities Use the Web, videos, and business case -- are linked from the Introduction. We'll discuss pros and cons to listing them on each page, too.

**Comment by slhenry** [comment]
I've updated each page with:

* an intro sentence like:
> This page provides a starting point for information that is particularly relevant to visual designers and user interface designers.

* a section at the end:
> ## More
> We encourage you to look around the W3C WAI website to find other information that you might be interested in.

* edited "First, skim... to:
> Even if you know a lot about accessibility, we encourage you to read **[Introduction to Web Accessibility](@@)**. It includes links to videos and to lots more information that you might want to read now or later.

Additional suggestions welcome!

**Comment by AndrewArch** [comment]
@slhenry wrote "... that you might want to read now or later"

Suggest adding (strongly hinting) that they might like to share some of these other resources

**Comment by slhenry** [comment]
Rewrote all pages after f2f input.

Put Andrews comment in new issue https://github.com/w3c/wai-audiences/issues/9

Closing this issue for now.
Shadi and others feel free to re-open if you want it to get more attention or discussion.

**Comment by nitedog** [comment]
I'm looking at the current beta site (don't know if there is another staging site) - do we want to have "content authors" as another role?

Also, it seems to me that these individual pages can be streamlined and merged into one (relatively short) page. I imagine a role-based sitemap. For example, many links go to the QuickRef, only with different parameters - these could be combined in a list of links and a suitable heading.

Having said that, I do not know if this has already been discussed in the redesign task force and so I will not re-open this issue. Please treat these comments at your own discretion.

**Comment by slhenry** [comment]
Hey Shadi. Sorry for not making it clear where the revised pages are. /WAI/beta is not updated yet.

The revised pages are available from: https://w3c.github.io/wai-website/roles/policy-makers/

We have not discussed merging them into one. The goals was for people to be able to get a very short, very focused page of stuff that was relevant to them. At this point, I don't see how merging them into one would meet that goal. Happy to revisit when we can work on ideas.

I added an issue for creating another role for content authors: https://github.com/w3c/wai-audiences/issues/10

Thanks for the comments at editors' discretion.
